// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/app/version/check": {
            "post": {
                "description": "Checks if the current app version needs an update or a forced update based on the platform.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "app-version"
                ],
                "summary": "Check App Version",
                "parameters": [
                    {
                        "description": "App Version Info",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.CheckAppVersionRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/auth/account/": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Removes a user account by their ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Delete Account",
                "responses": {}
            }
        },
        "/api/v1/auth/forget-password": {
            "post": {
                "description": "Initiates password recovery (Currently placeholder).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Forget Password",
                "parameters": [
                    {
                        "description": "User Email. 'email' field is required.",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.forgetPasswordRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/auth/guest": {
            "post": {
                "description": "Creates a temporary guest account. Does not require a request body. Returns a JWT token and the guest user's data.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Guest Login",
                "responses": {}
            }
        },
        "/api/v1/auth/login": {
            "post": {
                "description": "Authenticates a user using their username and password. Returns a JWT token and the user's data upon successful authentication.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "User Login",
                "parameters": [
                    {
                        "description": "Login Credentials. Both 'username' and 'password' are required.",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.loginRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/auth/logout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Invalidates the user session by blacklisting the current JWT token.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "User Logout",
                "responses": {}
            }
        },
        "/api/v1/auth/register": {
            "post": {
                "description": "Creates a new user account with the provided details. Returns a JWT token and the created user's data upon successful registration.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "User Registration",
                "parameters": [
                    {
                        "description": "Registration Details. 'fullname', 'username', 'password', 'college', 'department', and 'academic_year' (1-5) are required. 'gdg_track' is optional.",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.registerRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/profile/": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves the profile information of the currently authenticated user based on their JWT token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "Get User Profile",
                "responses": {}
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates the profile details (Fullname and Academic Year) of the currently authenticated user. Guest users are not allowed to update their profile.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "Update User Profile",
                "parameters": [
                    {
                        "description": "User Profile Update Data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.UserProfileRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/runs/": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves all runs for the authenticated user.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "runs"
                ],
                "summary": "Get User Runs",
                "responses": {
                    "200": {
                        "description": "List of runs retrieved successfully.",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/delivery.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/handlers.runResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized.",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/delivery.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "errors": {
                                            "$ref": "#/definitions/delivery.ErrorInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error.",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/delivery.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "errors": {
                                            "$ref": "#/definitions/delivery.ErrorInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/runs/submit": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Saves the stats of a completed game run for the authenticated user.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "runs"
                ],
                "summary": "Save Game Run",
                "parameters": [
                    {
                        "description": "Run Statistics",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.runRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/spacecrafts/": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves all spacecrafts owned by the authenticated user.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "spacecrafts"
                ],
                "summary": "Get Spacecrafts",
                "responses": {
                    "200": {
                        "description": "List of spacecrafts retrieved successfully.",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/delivery.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/handlers.spacecraftResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized.",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/delivery.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "errors": {
                                            "$ref": "#/definitions/delivery.ErrorInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error.",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/delivery.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "errors": {
                                            "$ref": "#/definitions/delivery.ErrorInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Adds a new spacecraft to the user's garage.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "spacecrafts"
                ],
                "summary": "Add Spacecraft",
                "parameters": [
                    {
                        "description": "Spacecraft Data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.spacecraftRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Spacecraft added successfully.",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/delivery.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handlers.spacecraftResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request.",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/delivery.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "errors": {
                                            "$ref": "#/definitions/delivery.ErrorInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized.",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/delivery.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "errors": {
                                            "$ref": "#/definitions/delivery.ErrorInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error.",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/delivery.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "errors": {
                                            "$ref": "#/definitions/delivery.ErrorInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/spacecrafts/{id}/equip": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Equips a specific spacecraft for the authenticated user, unequipping all others.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "spacecrafts"
                ],
                "summary": "Equip Spacecraft",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Spacecraft ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Spacecraft equipped successfully.",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/delivery.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handlers.spacecraftResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Error equipping spacecraft.",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/delivery.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "errors": {
                                            "$ref": "#/definitions/delivery.ErrorInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Error equipping spacecraft.",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/delivery.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "errors": {
                                            "$ref": "#/definitions/delivery.ErrorInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "403": {
                        "description": "Error equipping spacecraft.",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/delivery.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "errors": {
                                            "$ref": "#/definitions/delivery.ErrorInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Error equipping spacecraft.",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/delivery.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "errors": {
                                            "$ref": "#/definitions/delivery.ErrorInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error.",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/delivery.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "errors": {
                                            "$ref": "#/definitions/delivery.ErrorInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/spacecrafts/{id}/upgrade": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Upgrades a specific spacecraft's level for the authenticated user.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "spacecrafts"
                ],
                "summary": "Upgrade Spacecraft",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Spacecraft ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Spacecraft upgraded successfully.",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/delivery.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handlers.spacecraftResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Error upgrading spacecraft.",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/delivery.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "errors": {
                                            "$ref": "#/definitions/delivery.ErrorInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Error upgrading spacecraft.",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/delivery.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "errors": {
                                            "$ref": "#/definitions/delivery.ErrorInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "403": {
                        "description": "Error upgrading spacecraft.",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/delivery.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "errors": {
                                            "$ref": "#/definitions/delivery.ErrorInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Error upgrading spacecraft.",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/delivery.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "errors": {
                                            "$ref": "#/definitions/delivery.ErrorInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error.",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/delivery.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "errors": {
                                            "$ref": "#/definitions/delivery.ErrorInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "delivery.ErrorInfo": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "delivery.Meta": {
            "type": "object",
            "properties": {
                "last_page": {
                    "type": "integer"
                },
                "next": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "per_page": {
                    "type": "integer"
                },
                "prev": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "delivery.Response": {
            "type": "object",
            "properties": {
                "data": {},
                "errors": {
                    "$ref": "#/definitions/delivery.ErrorInfo"
                },
                "meta": {
                    "$ref": "#/definitions/delivery.Meta"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "handlers.CheckAppVersionRequest": {
            "type": "object",
            "required": [
                "platform",
                "version_code"
            ],
            "properties": {
                "platform": {
                    "type": "string",
                    "example": "android"
                },
                "version_code": {
                    "type": "integer",
                    "example": 105
                }
            }
        },
        "handlers.UserProfileRequest": {
            "type": "object",
            "required": [
                "academic_year",
                "fullname"
            ],
            "properties": {
                "academic_year": {
                    "type": "integer",
                    "maximum": 5,
                    "minimum": 1,
                    "example": 3
                },
                "fullname": {
                    "type": "string",
                    "example": "Mostafa Ahmed"
                }
            }
        },
        "handlers.forgetPasswordRequest": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "description": "User's email address (Required)",
                    "type": "string",
                    "example": "user@example.com"
                }
            }
        },
        "handlers.loginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "description": "User's password (Required)",
                    "type": "string",
                    "example": "P@ssw0rd123"
                },
                "username": {
                    "description": "User's username (Required)",
                    "type": "string",
                    "example": "mostafa_sensei"
                }
            }
        },
        "handlers.registerRequest": {
            "type": "object",
            "required": [
                "academic_year",
                "college",
                "department",
                "fullname",
                "password",
                "username"
            ],
            "properties": {
                "academic_year": {
                    "description": "Academic year from 1 to 5 (Required)",
                    "type": "integer",
                    "maximum": 5,
                    "minimum": 1,
                    "example": 3
                },
                "college": {
                    "description": "User's college (Required)",
                    "type": "string",
                    "example": "Computers \u0026 Info"
                },
                "department": {
                    "description": "User's department (Required)",
                    "type": "string",
                    "example": "Computer Science"
                },
                "fullname": {
                    "description": "Full Name (Required)",
                    "type": "string",
                    "example": "Mostafa Ahmed"
                },
                "gdg_track": {
                    "description": "GDG Track name (Optional, can be null)",
                    "type": "string",
                    "x-nullable": true,
                    "example": "Flutter"
                },
                "password": {
                    "description": "Password for login (Required)",
                    "type": "string",
                    "example": "P@ssw0rd123"
                },
                "username": {
                    "description": "Username for login (Required)",
                    "type": "string",
                    "example": "mostafa_sensei"
                }
            }
        },
        "handlers.runRequest": {
            "type": "object",
            "required": [
                "cause_of_death",
                "duration",
                "score"
            ],
            "properties": {
                "accuracy": {
                    "type": "number",
                    "example": 85.5
                },
                "bosses_defeated": {
                    "type": "integer",
                    "example": 1
                },
                "bugs_squashed": {
                    "type": "integer",
                    "example": 45
                },
                "cause_of_death": {
                    "type": "string",
                    "example": "NullPointerException Boss"
                },
                "coffee_cups": {
                    "type": "integer",
                    "example": 3
                },
                "duration": {
                    "type": "integer",
                    "example": 120
                },
                "max_flow_state": {
                    "type": "integer",
                    "example": 15
                },
                "score": {
                    "type": "integer",
                    "example": 1500
                },
                "stage_reached": {
                    "type": "string",
                    "example": "Staging Environment"
                }
            }
        },
        "handlers.runResponse": {
            "type": "object",
            "properties": {
                "accuracy": {
                    "type": "number",
                    "example": 85.5
                },
                "bosses_defeated": {
                    "type": "integer",
                    "example": 1
                },
                "bugs_squashed": {
                    "type": "integer",
                    "example": 45
                },
                "cause_of_death": {
                    "type": "string",
                    "example": "NullPointerException Boss"
                },
                "coffee_cups": {
                    "type": "integer",
                    "example": 3
                },
                "created_at": {
                    "type": "string",
                    "example": "2024-01-01T12:00:00Z"
                },
                "duration": {
                    "type": "integer",
                    "example": 120
                },
                "id": {
                    "type": "string",
                    "example": "uuid-1234"
                },
                "max_flow_state": {
                    "type": "integer",
                    "example": 15
                },
                "score": {
                    "type": "integer",
                    "example": 1500
                },
                "stage_reached": {
                    "type": "string",
                    "example": "Staging Environment"
                }
            }
        },
        "handlers.spacecraftRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "example": "Vim Fighter"
                },
                "rarity": {
                    "type": "string",
                    "example": "Epic"
                }
            }
        },
        "handlers.spacecraftResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "uuid-5678"
                },
                "is_active": {
                    "type": "boolean",
                    "example": true
                },
                "level": {
                    "type": "integer",
                    "example": 5
                },
                "name": {
                    "type": "string",
                    "example": "Vim Fighter"
                },
                "rarity": {
                    "type": "string",
                    "example": "Epic"
                },
                "unlocked_at": {
                    "type": "string",
                    "example": "2024-01-01T12:00:00Z"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Astro Wars API",
	Description:      "Astro Wars Backend API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
