// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {},
    "definitions": {
        "delivery.ErrorInfo": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "delivery.Meta": {
            "type": "object",
            "properties": {
                "last_page": {
                    "type": "integer"
                },
                "next": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "per_page": {
                    "type": "integer"
                },
                "prev": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "delivery.Response": {
            "type": "object",
            "properties": {
                "data": {},
                "errors": {
                    "$ref": "#/definitions/delivery.ErrorInfo"
                },
                "meta": {
                    "$ref": "#/definitions/delivery.Meta"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "domain.GDGInfo": {
            "type": "object",
            "properties": {
                "academic_year": {
                    "description": "Academic year between 1 and 5 (Required)",
                    "type": "integer",
                    "example": 3
                },
                "college": {
                    "description": "User's college (Optional, can be null)",
                    "type": "string",
                    "x-nullable": true,
                    "example": "Engineering"
                },
                "community_role": {
                    "description": "Role in the community (Required)",
                    "type": "string",
                    "example": "member"
                },
                "department": {
                    "description": "User's department (Optional, can be null)",
                    "type": "string",
                    "x-nullable": true,
                    "example": "Computer Science"
                },
                "gdg_track": {
                    "description": "GDG Track (Optional, can be null)",
                    "type": "string",
                    "x-nullable": true,
                    "example": "Web Development"
                },
                "system_role": {
                    "description": "Role in the system (Required)",
                    "type": "string",
                    "example": "player"
                }
            }
        },
        "domain.User": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "fullname": {
                    "description": "Full name of the user (Required)",
                    "type": "string",
                    "example": "John Doe"
                },
                "id": {
                    "type": "string"
                },
                "info": {
                    "description": "Embedded GDG information (Required)",
                    "allOf": [
                        {
                            "$ref": "#/definitions/domain.GDGInfo"
                        }
                    ]
                },
                "stats": {
                    "description": "Embedded user statistics (Required)",
                    "allOf": [
                        {
                            "$ref": "#/definitions/domain.UserStats"
                        }
                    ]
                },
                "updated_at": {
                    "type": "string"
                },
                "username": {
                    "description": "Unique username (Required)",
                    "type": "string",
                    "example": "john_doe"
                }
            }
        },
        "domain.UserStats": {
            "type": "object",
            "properties": {
                "coins": {
                    "description": "User coins (Required)",
                    "type": "integer",
                    "example": 250
                },
                "current_streak": {
                    "description": "Current login streak (Required)",
                    "type": "integer",
                    "example": 3
                },
                "experience": {
                    "description": "User experience points (Required)",
                    "type": "integer",
                    "example": 1500
                },
                "last_played_at": {
                    "description": "Last played timestamp (Optional, can be null)",
                    "type": "string",
                    "x-nullable": true,
                    "example": "2023-10-01T15:00:00Z"
                },
                "level": {
                    "description": "User level (Required)",
                    "type": "integer",
                    "example": 5
                },
                "max_streak": {
                    "description": "Max login streak (Required)",
                    "type": "integer",
                    "example": 10
                },
                "points": {
                    "description": "User points (Required)",
                    "type": "integer",
                    "example": 1200
                }
            }
        },
        "handlers.authResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "description": "JWT Authentication Token (Required in response)",
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                },
                "user": {
                    "description": "The authenticated user's profile data (Required in response)",
                    "allOf": [
                        {
                            "$ref": "#/definitions/domain.User"
                        }
                    ]
                }
            }
        },
        "handlers.forgetPasswordRequest": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "description": "User's email address (Required)",
                    "type": "string",
                    "example": "user@example.com"
                }
            }
        },
        "handlers.loginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "description": "User's password (Required)",
                    "type": "string",
                    "example": "P@ssw0rd123"
                },
                "username": {
                    "description": "User's username (Required)",
                    "type": "string",
                    "example": "mostafa_sensei"
                }
            }
        },
        "handlers.registerRequest": {
            "type": "object",
            "required": [
                "academic_year",
                "college",
                "department",
                "fullname",
                "password",
                "username"
            ],
            "properties": {
                "academic_year": {
                    "description": "Academic year from 1 to 5 (Required)",
                    "type": "integer",
                    "maximum": 5,
                    "minimum": 1,
                    "example": 3
                },
                "college": {
                    "description": "User's college (Required)",
                    "type": "string",
                    "example": "Computers \u0026 Info"
                },
                "department": {
                    "description": "User's department (Required)",
                    "type": "string",
                    "example": "Computer Science"
                },
                "fullname": {
                    "description": "Full Name (Required)",
                    "type": "string",
                    "example": "Mostafa Ahmed"
                },
                "gdg_track": {
                    "description": "GDG Track name (Optional, can be null)",
                    "type": "string",
                    "x-nullable": true,
                    "example": "Flutter"
                },
                "password": {
                    "description": "Password for login (Required)",
                    "type": "string",
                    "example": "P@ssw0rd123"
                },
                "username": {
                    "description": "Username for login (Required)",
                    "type": "string",
                    "example": "mostafa_sensei"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Astro Wars API",
	Description:      "Astro Wars Backend API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
