// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/auth/account/": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Removes a user account by their ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Delete Account",
                "responses": {}
            }
        },
        "/api/v1/auth/forget-password": {
            "post": {
                "description": "Initiates password recovery (Currently placeholder).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Forget Password",
                "parameters": [
                    {
                        "description": "User Email. 'email' field is required.",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.forgetPasswordRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/auth/guest": {
            "post": {
                "description": "Creates a temporary guest account. Does not require a request body. Returns a JWT token and the guest user's data.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Guest Login",
                "responses": {}
            }
        },
        "/api/v1/auth/login": {
            "post": {
                "description": "Authenticates a user using their username and password. Returns a JWT token and the user's data upon successful authentication.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "User Login",
                "parameters": [
                    {
                        "description": "Login Credentials. Both 'username' and 'password' are required.",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.loginRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/auth/logout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Invalidates the user session by blacklisting the current JWT token.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "User Logout",
                "responses": {}
            }
        },
        "/api/v1/auth/register": {
            "post": {
                "description": "Creates a new user account with the provided details. Returns a JWT token and the created user's data upon successful registration.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "User Registration",
                "parameters": [
                    {
                        "description": "Registration Details. 'fullname', 'username', 'password', 'college', 'department', and 'academic_year' (1-5) are required. 'gdg_track' is optional.",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.registerRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/api/v1/profile/": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves the profile information of the currently authenticated user based on their JWT token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "Get User Profile",
                "responses": {}
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates the profile details (Fullname and Academic Year) of the currently authenticated user. Guest users are not allowed to update their profile.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "Update User Profile",
                "parameters": [
                    {
                        "description": "User Profile Update Data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.UserProfileRequest"
                        }
                    }
                ],
                "responses": {}
            }
        }
    },
    "definitions": {
        "handlers.UserProfileRequest": {
            "type": "object",
            "required": [
                "academic_year",
                "fullname"
            ],
            "properties": {
                "academic_year": {
                    "type": "integer",
                    "maximum": 5,
                    "minimum": 1,
                    "example": 3
                },
                "fullname": {
                    "type": "string",
                    "example": "Mostafa Ahmed"
                }
            }
        },
        "handlers.forgetPasswordRequest": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "description": "User's email address (Required)",
                    "type": "string",
                    "example": "user@example.com"
                }
            }
        },
        "handlers.loginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "description": "User's password (Required)",
                    "type": "string",
                    "example": "P@ssw0rd123"
                },
                "username": {
                    "description": "User's username (Required)",
                    "type": "string",
                    "example": "mostafa_sensei"
                }
            }
        },
        "handlers.registerRequest": {
            "type": "object",
            "required": [
                "academic_year",
                "college",
                "department",
                "fullname",
                "password",
                "username"
            ],
            "properties": {
                "academic_year": {
                    "description": "Academic year from 1 to 5 (Required)",
                    "type": "integer",
                    "maximum": 5,
                    "minimum": 1,
                    "example": 3
                },
                "college": {
                    "description": "User's college (Required)",
                    "type": "string",
                    "example": "Computers \u0026 Info"
                },
                "department": {
                    "description": "User's department (Required)",
                    "type": "string",
                    "example": "Computer Science"
                },
                "fullname": {
                    "description": "Full Name (Required)",
                    "type": "string",
                    "example": "Mostafa Ahmed"
                },
                "gdg_track": {
                    "description": "GDG Track name (Optional, can be null)",
                    "type": "string",
                    "x-nullable": true,
                    "example": "Flutter"
                },
                "password": {
                    "description": "Password for login (Required)",
                    "type": "string",
                    "example": "P@ssw0rd123"
                },
                "username": {
                    "description": "Username for login (Required)",
                    "type": "string",
                    "example": "mostafa_sensei"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Astro Wars API",
	Description:      "Astro Wars Backend API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
