import 'dart:convert';
import 'package:flutter/services.dart';

/// CI-style mission structure: a sector is a fixed list of typed waves
/// ending with a boss. Missions ship as JSON in `assets/missions/`
/// (generated by `Python/scripts/generate_missions.py`); anything missing
/// falls back to the procedural generator below.
enum WaveType { formation, swoop, meteor, bonus }

class MissionWave {
  final WaveType type;
  final int rows;
  final int cols;
  final double speedMult;
  final int giftShower;

  const MissionWave({
    required this.type,
    this.rows = 2,
    this.cols = 5,
    this.speedMult = 1.0,
    this.giftShower = 0,
  });

  factory MissionWave.fromJson(Map<String, dynamic> json) => MissionWave(
        type: WaveType.values.firstWhere(
          (t) => t.name == json['type'],
          orElse: () => WaveType.formation,
        ),
        rows: (json['rows'] as num?)?.toInt() ?? 2,
        cols: (json['cols'] as num?)?.toInt() ?? 5,
        speedMult: (json['speedMult'] as num?)?.toDouble() ?? 1.0,
        giftShower: (json['giftShower'] as num?)?.toInt() ?? 0,
      );

  String get label => switch (type) {
        WaveType.formation => 'CHICKEN FORMATION',
        WaveType.swoop => 'SWOOP STORM',
        WaveType.meteor => 'METEOR STORM',
        WaveType.bonus => 'BONUS HARVEST',
      };
}

class SectorMission {
  final int sector;
  final List<MissionWave> waves;

  const SectorMission({required this.sector, required this.waves});

  int get totalWaves => waves.length;

  MissionWave waveAt(int index) =>
      index < waves.length ? waves[index] : waves.last;

  static Future<SectorMission> load(int sector) async {
    try {
      final raw = await rootBundle
          .loadString('assets/missions/sector_$sector.json');
      final json = jsonDecode(raw) as Map<String, dynamic>;
      final waves = (json['waves'] as List)
          .map((w) => MissionWave.fromJson(w as Map<String, dynamic>))
          .toList();
      if (waves.isEmpty) return SectorMission.fallback(sector);
      return SectorMission(sector: sector, waves: waves);
    } catch (_) {
      return SectorMission.fallback(sector);
    }
  }

  /// Procedural fallback for sectors without a JSON file.
  factory SectorMission.fallback(int sector) {
    final waves = <MissionWave>[];
    final count = 6 + (sector.clamp(1, 5));
    for (int i = 0; i < count; i++) {
      final roll = i % 5;
      if (roll == 3) {
        waves.add(MissionWave(
            type: WaveType.meteor, speedMult: 1.0 + sector * 0.1));
      } else if (roll == 4) {
        waves.add(const MissionWave(
            type: WaveType.bonus, rows: 2, cols: 4, giftShower: 3));
      } else if (roll == 2) {
        waves.add(MissionWave(
            type: WaveType.swoop,
            rows: 2 + sector ~/ 2,
            cols: 5,
            speedMult: 1.0 + sector * 0.1));
      } else {
        waves.add(MissionWave(
          type: WaveType.formation,
          rows: (2 + sector ~/ 2).clamp(2, 4),
          cols: (5 + sector ~/ 2).clamp(5, 8),
          speedMult: 1.0 + sector * 0.1,
        ));
      }
    }
    return SectorMission(sector: sector, waves: waves);
  }
}
